### ISSUE TITLE
Incorrect documentation of line tracing feature

### ISSUE THREAD

**Issue by wmnnd** [krzysu/flot.tooltip#100]
Hey there,

it seems to me that line tracing is activated with
`lines: true` and not, like suggested in the documentation, with `lines: {
        track: true
    }
`.

Besides that, thanks for the great plugin :+1:

**Comment by Roundaround** [comment]
You are absolutely correct.  That was a change since the feature's introduction where I guess I just forgot to change the documentation.  I appreciate the heads up!
