### ISSUE TITLE
Add ability to position tooltip relative to datapoint rather than mouse cursor

### ISSUE THREAD

**Issue by trevorgehman** [krzysu/flot.tooltip#104]
Flot provides a tooltip example where they do this, and others have done this: http://designmodo.com/demo/interactivegraph/

But I prefer using a plugin for the tooltip, as it's easier to control. Is there already a way to accomplish this easily?

**Comment by Roundaround** [comment]
I don't imagine this will be difficult.  I think I already know where I can get the positional data in the existing infrastructure to do it  I'll slate it for the next release, and let you know when I have a stable nightly build that has it!
