### ISSUE TITLE
cssClass can't be used to set backgroundColor since element overrides it?

### ISSUE THREAD

**Issue by janicki** [krzysu/flot.tooltip#106]
I just upgraded to 8.5 (and the latest flot version) and tried to use the cssClass feature.  Unfortunately, the tooltip div defines its own background color in the element's style attribute, so my cssClass can't effect it.  I'm a noobie... Am I missing something?  It seems like only the dynamic attributes (e.g. position) should be in the element's style, and anything else should be in CCS classes, so they can be cascaded (and I can overwrite them), unless my CSS understanding is faulty.

I can understand if you don't want to include a separate css file, but as a workaround maybe tooltip could avoid setting any non-dynamic properties (i.e. background and white-space) when the user has defined a value for cssClass?

**Comment by krzysu** [comment]
Hi,
in documentation you can find another parameter:

defaultTheme : plugin have default theme build-in but here you can switch it off and adjust look of tip styling .flotTip (or whatever you set the class option to) in your CSS

so just set defaultTheme to false and then you can write any CSS you want

**Comment by janicki** [comment]
Thanks!!
