### ISSUE TITLE
unexpected rgb display in custom data example

### ISSUE THREAD

**Issue by kenirwin** [krzysu/flot.tooltip#108]
Looking at the "Using custom data inside a tooltip" example, I see an unexpected result. 

#### Screenshot:

![flot-tooltip-rgb](https://cloud.githubusercontent.com/assets/1894561/7965449/904a4a9a-09eb-11e5-9c34-3bc1b4a2c656.png) 

#### Code: 
`tooltip: {
                        show: true,
                        content: '%s: you scored %y.0% in %ct',
                        shifts: {
                            x: -60,
                            y: 25
                        }
                    }`
#### Discussion:
The `%c` in `%ct` renders an rgb code. I'm not sure what the intent was with this example, but I don't think this was it. `%ct` makes me think the user was expecting a count, but from context I would be expecting perhaps the name of the question from the serverData definition: 
`var serverData = {
                    testName: 'Driving Test',
                    questions: [
                        { number: 1, score: 20, name: 'Difficult question' },
                        { number: 2, score: 47, name: 'Who has more priority?' },
                        { number: 3, score: 19, name: 'Question 3' },
                        { number: 4, score: 63, name: 'Final question' }
                    ]
                };`

Perhaps someone who knows the intent of this example can improve it.

**Comment by kenirwin** [comment]
I think I've figured out what's going on here and will submit a pull request to fix it soon.

**Comment by krzysu** [comment]
Hi,
thank you for all your contributions. I see you are doing really good job here!

Best

**Comment by kenirwin** [comment]
Thanks =)

**Comment by kenirwin** [comment]
Fixed by pull request #117
