### ISSUE TITLE
problems in combination with flot-downsample plugin

### ISSUE THREAD

**Issue by mojoaxel** [krzysu/flot.tooltip#126]
If the tooltip plugin ist used together with the [downsample plugin](sveinn-steinarsson/flot-downsample) the tooltip plugin sometimes tries to access out of bounds data on hover.

The error occours in [x = item.series.data[item.dataIndex][0];](krzysu/flot.tooltip/blob/master/js/jquery.flot.tooltip.js#L362) because `item.dataIndex` is sometimes greater than the downsampled `series.data` array.

**Comment by krzysu** [comment]
hi, I can only encourage you to fix it on your own and send pull request, I'm not actively maintaining this plugin anymore

**Comment by mojoaxel** [comment]
This has actually nothing to do with the downsampling plugin. 
Closing this and opening a new issue if problem is better understood.
