### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by softshape** [krzysu/flot.tooltip#127]
Hi all,

here's my config -
```javascript
  $.plot($(".flot"), [d1],  { 
      bars: { show: true }, 
      xaxis: { mode: "time" }, 
      zoom: { interactive: true }, 
      pan: { interactive: true },
      grid:  { hoverable: true }, //important! flot.tooltip requires this
      tooltip: {
        show: true,
        content: "x: %x, y: %y"
      }
  });
```
Either it's not compatible with time plugin, zoom/pan, or bars mode?

**Comment by Roundaround** [comment]
It'd be helpful if you could give a little more information.  What other flot plugins (with versions) are you using?  If you open the debug console (F12), does it give errors?

**Comment by softshape** [comment]
It seems that the reason is in the flot itself. It just doesn't handle hover event for bars if bar width is less than 3-4 pixels.
