### ISSUE TITLE
Bower install of v0.8.5 is getting the 2015-05-11 build instead of 2015-06-12

### ISSUE THREAD

**Issue by DavidPautet** [krzysu/flot.tooltip#135]
Hi,

I am looking for the 2015-06-12 build (since I need a fix for replacing in the right order %ct and %c tokens) but when fetching the v0.8.5 using ("bower install") I am getting the 2015-05-11 build which is not containing my fix....

Do you know why and how I can arrange this ?

Thanks for your help.
David.

**Comment by krzysu** [comment]
seems like new version was not tagged (released), I will fix it later today

**Comment by krzysu** [comment]
0.8.6 released with all changes since May 2015, let me know if it works for you. Closing for now.
