### ISSUE TITLE
%y not working on pie chart

### ISSUE THREAD

**Issue by MichaelQuint** [krzysu/flot.tooltip#144]
Hello,

I cant seem to get %y working on my flot pie chart, it just shows %y. it works fine on my line chart.

**Comment by krzysu** [comment]
I'm not sure now if %y is supposed to work with pie chart, I don't see that used in the example here https://github.com/krzysu/flot.tooltip/blob/master/examples/pie.html

also in the source code I see:

```
%p -> percent
%n -> value (not percent) of pie chart
```

let me know if that solves your problem

**Comment by MichaelQuint** [comment]
Yes! %n works, sorry about that. The template I am using used %y and since it worked for the line chart I assumed it would be the same. Thanks again!
