### ISSUE TITLE
Tooltip showing under content when using a Pie Chart

### ISSUE THREAD

**Issue by mortenbirkelund** [krzysu/flot.tooltip#147]
Hi

I have a weird problem where the Tooltips are not visible whenever I have a pie chart on the screen. Whenever the pie chart is not rendered (if i make an error in the code for rendering it) then the tooltips are showing perfectly fine for all the other charts. But whenever the Pie Chart is rendered then the tooltip is shown underneath the content.
You can see the error in the first and second image, and in the third you can see what happens whenever i make an error in the code for the Pie Chart, so that it is not rendered. 

![1](https://cloud.githubusercontent.com/assets/8955039/20915192/8bf433c4-bb84-11e6-8c75-2000cdb9e561.PNG)

![2](https://cloud.githubusercontent.com/assets/8955039/20915191/8bead040-bb84-11e6-8c4f-c0063b6dedf9.PNG)

![3](https://cloud.githubusercontent.com/assets/8955039/20915190/8be284da-bb84-11e6-9bd3-34a0cc7de226.PNG)

Any quick fix for this problem?

**Comment by krzysu** [comment]
my first thought is to check CSS z-index of your chart and tooltip

**Comment by mortenbirkelund** [comment]
Found the problem. 
Commenting out the following options in the piechart solved the problem. Not exactly sure why...

//defaultTheme: false

**Comment by krzysu** [comment]
that means you are using now the defaultTheme of tooltip, what sets z-index to default value. defaultTheme is just some default CSS styling for your tooltip

**Comment by mortenbirkelund** [comment]
Thanks for the explanation. Hope this can help other with similar problem.
