### ISSUE TITLE
tooltip value is not showing correctly

### ISSUE THREAD

**Issue by sumit1191** [krzysu/flot.tooltip#153]
I am using tooltip but data on tooltip is showing incorrectly . I have two bar on bar is showing correctly but other is showing wrong. i am attaching image1 and image2 . In the image1 tooltip data is showing correctly on the green bar while in image2 on blue bar showing tooltip data in incorrectly. on the blue bar should also showing X axis value as green bar but its showing 20 instead of COD maintenance.

Please suggest someone.
![image1](https://user-images.githubusercontent.com/32646675/31351538-1c1da5f0-ad49-11e7-9396-de963ec09850.jpg)
![image2](https://user-images.githubusercontent.com/32646675/31351539-1c23c52a-ad49-11e7-9633-0901b0cf52c2.jpg)

**Comment by sumit1191** [comment]
Can anyone help me out ?

**Comment by sumit1191** [comment]
<div ui-jq="plot" data-ng-if="rbjc.showGraph" ui-options="
                                      [ 
                                        { label: '&nbsp;Actual', data: {{rbjc.GraphTotalRevenue}} },
                                        { label: '&nbsp;Goal', data: {{rbjc.GraphTotalRevenueGoal}} },
                                 
                                      ],
                                      {
                                        bars: { show: true, fill: true, lineWidth: 1, order: 1, fillColor: { colors: [{ opacity: 0.5 }, { opacity: 0.9}] } },
                                        colors: ['{{rbjc.color.actual}}', '{{rbjc.color.goal}}'],
                                        series: { shadowSize: 1 },
                                        xaxis:{ font: { color: '#000' }, position: 'bottom', ticks: {{rbjc.GraphTicks}}, tickOptions: { angle: 30 } },
                                        yaxis:{ font: { color: '#333' }, min: 0 },
                                        grid: { hoverable: true, clickable: true, borderWidth: 0, color: '#ccc' },
                                        tooltip: true
                                        
                                      }
                                    "
                            data-ui-refresh="rbjc.GraphTotalRevenue" style="height: 400px">

**Comment by krzysu** [comment]
this repo in no longer maintained so I can only suggest to look into source code, debug values displayed in your use-case and fix it for yourself

**Comment by sumit1191** [comment]
@krzysu 
The issue is with my code or in Jquery.flot.tooltip.min.js ? Can you please suggest at least ?

**Comment by sumit1191** [comment]
<div ui-jq="plot" data-ng-if="rbjc.showGraph" ui-options="
                                      [ 
                                        { label: '&nbsp;Actual', data: {{rbjc.GraphTotalRevenue}} },
                                        { label: '&nbsp;Goal', data: {{rbjc.GraphTotalRevenueGoal}} },
                                 
                                      ],
                                      {
                                        bars: { show: true, fill: true, lineWidth: 1, order: 1, fillColor: { colors: [{ opacity: 0.5 }, { opacity: 0.9}] } },
                                        colors: ['{{rbjc.color.actual}}', '{{rbjc.color.goal}}'],
                                        series: { shadowSize: 1 },
                                        xaxis:{ font: { color: '#000' }, position: 'bottom', ticks: {{rbjc.GraphTicks}}, tickOptions: { angle: 30 } },
                                        yaxis:{ font: { color: '#333' }, min: 0 },
                                        grid: { hoverable: true, clickable: true, borderWidth: 0, color: '#ccc' },
                                        tooltip: true
                                        
                                      }
                                    "
                            data-ui-refresh="rbjc.GraphTotalRevenue" style="height: 400px">

**Comment by krzysu** [comment]
I don't know :) you can check other issues here, maybe https://github.com/krzysu/flot.tooltip/issues/65 is something similar to what you have? or https://github.com/krzysu/flot.tooltip/issues/94 ?
