### ISSUE TITLE
Tooltip does not replace x label by given x.

### ISSUE THREAD

**Issue by jevanlingen** [krzysu/flot.tooltip#18]
If you have given your xaxis your own label with ticks, the tooltip does not show those ticks.

E.G.

```
data: [ [0, 450], [1, 550], [2, 320], [3, 700] ],
xaxis: {
     ticks: [
       [0, "great"],
       [1, "greater"],
       [2, "greatest"]
     ]
}   
```

Could you fix this in your next version?

---

**N.B**. For those whom need a quick fix, go to your jquery.flot.tooltip to line 181. 

There you should see:

```
if(typeof item.series.xaxis.tickFormatter !== 'undefined') {
```

Change that line to:

```
 if(typeof item.series.xaxis.tickFormatter !== 'undefined' && item.series.xaxis.ticks.length == 0) {
```

And add above these line:

```
// change x from number to given label, if given
if(item.series.xaxis.ticks.length != 0) {
   content = content.replace(xPattern, item.series.xaxis.ticks[item.dataIndex].label);
}
```

Done :D.

**Comment by emakarov** [comment]
Hi
Could you post a short example how to display tick labels in tooltips?
