### ISSUE TITLE
Add on click support.

### ISSUE THREAD

**Issue by miguelcobain** [krzysu/flot.tooltip#19]
On mobile devices, hover doesn't work as expected. It would be great to show the tooltip on click, and let the tooltip stay there.

**Comment by onli** [comment]
I am searching for support of this as well, and found nothing in the latest version. Am I missing an option or did the feature get dropped?

**Comment by krzysu** [comment]
feel free to dig into source code of this plugin and add expected behavior yourself. source code is simple. pull requests are always welcomed.

**Comment by onli** [comment]
Will do and send in a PR. Thanks
