### ISSUE TITLE
Tooltip doesn't appear over piechart labels

### ISSUE THREAD

**Issue by sheffieldnikki** [krzysu/flot.tooltip#73]
When you mouseover a piechart the tooltip appears fine, but if you mouseover label text (over the piechart) the tooltip disappears - presumably because the event isn't propagating to the parent? A javascript fix for this would be good, but a quick CSS workaround is:

```
.pieLabel {
  pointer-events: none;
  }
```

but that doesn't work in IE until v11.

**Comment by nguyendt214** [comment]
Add in your style file:
#flotTip{
  z-index: 999;
}

That's it. :)
