### ISSUE TITLE
Incorrect date/time displayed for time axis mode

### ISSUE THREAD

**Issue by firmanw** [krzysu/flot.tooltip#92]
Hi,
I'm currently using the final version 0.8.4, the tooltip always displayed the date/time before current hovered. For example August being hovered but the tooltip displayed as July. I have tested using the Flot examples http://www.flotcharts.org/flot/examples/axes-time/index.html and get the same result, the quarter and year also incorrect.

![flot-tooltip-month](https://cloud.githubusercontent.com/assets/319658/4029298/a64735dc-2c4d-11e4-956e-dc6d40bf3d16.jpg)
![flot-tooltip-quarter](https://cloud.githubusercontent.com/assets/319658/4029299/a64d5764-2c4d-11e4-9b3d-a16972d949e0.jpg)
![flot-tooltip-year](https://cloud.githubusercontent.com/assets/319658/4029300/a654bad6-2c4d-11e4-83d4-7c1c0a4c8b90.jpg)

**Comment by mattcameron** [comment]
I also experienced this problem and eventually realised that the problem was due to the difference between my timezone (GMT +11) and the default timezone used by flot.

I solved it by adding `xaxis: { timezone: 'browser' }`

**Comment by krzysu** [comment]
@mattcameron thank you for solving the issue, I labeled it for the future reference and I'm closing it for now
